### ISSUE TITLE
1.2 機械学習とは何か？ 内の誤植

### ISSUE THREAD

**Issue by AkihiroKusuda** [hacarus/interpretable-ml-book-ja#39]
> ステップ2：これらの情報を道路標識検出モデル、債務評価モデル、住宅価格予測モデルなどを生成する機外学習のアルゴリズムに入力します。

1.2内の上記の文章内の「機外学習」は「機械学習」の誤植かと思います。

**Comment by yushiro-yamashita** [comment]
@AkihiroKusuda 
ご指摘いただきありがとうございます。対応いたしました。
