### ISSUE TITLE
5.9 シャープレイ値での誤訳

### ISSUE THREAD

**Issue by KENJI-JIN** [hacarus/interpretable-ml-book-ja#44]
日本語訳いただきありがとうございます。前々から注目していたサイトだったので、読みやすくなり、大変助かります。

5.9 シャープレイ値で駐車場と訳されているところは原文及び絵から駐車場ではなく、公園だと思います。
駐車場と記載されていると絵との関連性がなく、読みにくくなっているので修正いただけると助かります。

**Comment by yushiro-yamashita** [comment]
@KENJI-JIN 
ご指摘いただきありがとうございます。そのようにおっしゃっていただけると、翻訳活動の励みになります。
該当箇所に対応いたしました。
